### ISSUE TITLE
How big is the size of generated docs?

### ISSUE THREAD

**Issue by tesuji** [TyPR124/stdrs_dev_script#2]
I'm using stdrs.dev. The site is really nice when I need to examine internal of std lib.
I have some questions to ask about your project:
* How big is the generated docs? On each target and total.
* Domain cost of stdrs.dev, also the cost for the server, and which party provides that ?
* Can we use github page for hosting instead?

I really appreciate your work here.

**Comment by TyPR124** [comment]
Hi, sorry I didn't see this earlier.

* The docs are about 418MB for Linux, 378 for Windows, and 400 for Mac. So ~1.2GB in total. I'd expect this to grow pretty slowly over time, but don't have any data on hand to back that up.
* The entire project, other than this repo, is effectively hosted with Google. I pay the cost of all hosting currently, and as it stands I don't expect this to become a problem any time soon. Cost of the domain is $12/year, and cost of running the site is roughly $30/month. About $20 of that is "HTTP Load Balancing: Global Forwarding Rule Minimum Service Charge." The bulk of the remaining cost is in syncing updated docs every night. The next highest cost is compute time, which was $0.66 in December.
* It should be feasible to host the docs somewhere other than a Google Bucket, which would potentially eliminate the $20 load balancing fee and maybe reduce syncing cost. I've recently heard about Google Firebase, which could be a cheaper option. Github pages could be another valid option. As of now, I haven't looked into either of these options.

I am open to other ideas as well.

For clarity, all costs listed are in USD from December 2020.

**Comment by tesuji** [comment]
I [forked your project](https://gitlab.com/lzutao/rust-internal-std-docs) and use gitlab CI to build and publish the generated docs to gitlab pages. The result page is here: <https://lzutao.gitlab.io/rust-internal-std-docs/nightly/x86_64-unknown-linux-gnu/std/index.html>. The `nav.js` is broken because the gitlab pages is not operate at domain root.
I had to drop apple target since the artifact size is too big to deploy (1.26G). Though I read that gitlab allows 10GB per repo. Maybe this is just a limitation for gitlab pages.
The hard and slow part is cloning Rust repo and initializing all submodules.
The doc gen part is about 2 minutes per target.

I think the biggest thing to cut down computation cost (time and CPU) is to make `cargo doc` works directly on `rust-src` component of rustup,
just like `-Z build-std` flag currently does. But that's a hard part and I don't have enough motivation to finish it.

**Comment by TyPR124** [comment]
Looks like Github Pages does have a 1G limit: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages

> Published GitHub Pages sites may be no larger than 1 GB.

EDIT: Just realized you are using GitLAB, not GitHUB. Oops.

Unless that limit could be waived entirely (or increased to a point that it is effectively waived entirely), I don't think I'm comfortable using Pages even with only two targets, as it would require me to keep a much closer eye on sizes than I do now. Also, in the long run, I may want to add additional targets and/or keep (one or more) version(s) of stable docs as well.

> The hard and slow part is cloning Rust repo and initializing all submodules.

Yep. For this reason, I'm using a VM with persistent storage to generate the docs. The storage cost was about $0.01 last month, so in my estimation the savings in compute time (and RAM time) are well-worth the persistent storage cost.

I suppose if this could be run via free CI instead (it would need to run on a daily schedule, and I'd need to be sure I won't run into some limitation), then the extra CPU time required to clone the repo and submodules wouldn't be an issue.

Using the rust-src component is potentially a good idea, hadn't thought of that.

I may try testing a Firebase hosting solution at some point soon, though it isn't a high priority for me right now.
